"use client";

import { useState } from "react";
import { CheckCircle2, FileSpreadsheet, Upload, XCircle } from "lucide-react";

type Preview = { columns: string[]; mapping: Record<string, string>; totalRows: number; invalidProcessNumbers: number; preview: Array<Record<string, string | boolean>> };

export default function ImportarPage() {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<Preview | null>(null);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  async function previewFile() { if (!file) return; setLoading(true); setMessage(""); const form = new FormData(); form.append("file", file); const response = await fetch("/api/importar", { method: "POST", body: form }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error ?? "Falha ao ler arquivo."); setPreview(data); }
  async function commit() { if (!file || !preview) return; setLoading(true); const form = new FormData(); form.append("file", file); form.append("mapping", JSON.stringify(preview.mapping)); const response = await fetch("/api/importar?mode=commit", { method: "POST", body: form }); const data = await response.json(); setLoading(false); setMessage(response.ok ? `${data.imported} processos importados e ${data.updated} atualizados.` : data.error); }
  const [clearing, setClearing] = useState(false);
  async function clearDatabase() { if (!confirm("TEM CERTEZA? Esta ação apagará permanentemente TODOS os processos, clientes e movimentos do banco de dados.")) return; setClearing(true); const response = await fetch("/api/admin/limpar-banco", { method: "DELETE" }); const data = await response.json(); setClearing(false); setMessage(response.ok ? data.message : data.error); if (response.ok) { setPreview(null); setFile(null); } }
  return <main className="import-page"><div className="import-header"><div><p className="eyebrow">DADOS DE ORIGEM</p><h1>Importar processos</h1><p>Traga sua planilha para o radar jurídico sem alterar o arquivo original.</p></div><div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}><button onClick={clearDatabase} disabled={clearing} style={{ background: '#ffebee', color: '#c62828', border: '1px solid #ffcdd2', padding: '0.4rem 0.8rem', borderRadius: '4px', cursor: 'pointer', fontWeight: 500, fontSize: '0.85rem' }}>{clearing ? "Limpando..." : "Limpar Banco"}</button><a href="/" className="back-link">Voltar ao dashboard</a></div></div><section className="import-panel"><div className="upload-zone"><FileSpreadsheet size={28} /><h2>Selecione sua planilha</h2><p>Formatos aceitos: .xlsx, .xls ou .csv · até 10 MB</p><label className="upload-button"><Upload size={16} />{file ? file.name : "Escolher arquivo"}<input type="file" accept=".xlsx,.xls,.csv" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); setMessage(""); }} /></label></div>{file && <div className="import-actions"><button className="sync-button" onClick={previewFile} disabled={loading}>{loading ? "Lendo..." : "Pré-visualizar"}</button>{preview && <button className="commit-button" onClick={commit} disabled={loading}>Importar no banco</button>}</div>}{message && <p className="import-message">{message}</p>}</section>{preview && <section className="preview-panel"><div className="preview-heading"><div><p className="eyebrow">PRÉ-VISUALIZAÇÃO</p><h2>{preview.totalRows} linhas encontradas</h2></div><span className={preview.invalidProcessNumbers ? "warning-count" : "valid-count"}>{preview.invalidProcessNumbers ? <XCircle size={15} /> : <CheckCircle2 size={15} />}{preview.invalidProcessNumbers ? `${preview.invalidProcessNumbers} números para revisar` : "Números CNJ reconhecidos"}</span></div><div className="mapping-list">{Object.entries(preview.mapping).map(([field, column]) => <span key={field}><b>{field}</b> ← {column}</span>)}</div><div className="preview-table"><table><thead><tr>{Object.keys(preview.preview[0] ?? {}).slice(0, 6).map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{preview.preview.slice(0, 8).map((row, index) => <tr key={index}>{Object.values(row).slice(0, 6).map((value, cellIndex) => <td key={cellIndex}>{String(value)}</td>)}</tr>)}</tbody></table></div></section>}</main>;
}
